config/routes.rb
Rails.application.routes.draw do
  	
  	root 'pages#home'
  	devise_for :users
	 resources :categories
    resources :products
    resources :purchases
    
    get 'profile' => 'pages#profile'

    get 'dashboard' => 'purchases#dashboard'

   
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


    #get 'welcome' => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="container" id="productcontainer">
	<div class="row">
		<div class="col-md-3">
			<h3 class="text-center">Categorías</h3>
			<ul class="listgroup">
				<% @categories.each do |category| %>
					<li class="list-group-item"><%= link_to category.name, root_path(category_id: category.id) %></li>
				<% end %>
			</ul>
		</div>

		<div class="col-md-9">
			<% if @products.size > 0 %>
				<% @products.each do |product| %>
				<div class="col-sm-6 col-md-4">
					<div class="thumbnail">
						<%= image_tag product.image.url(:thumb), class: 'image-responsive' %>
						 <!-- <img src="http://fakeimg.pl/350x200/ff0000/000" alt="..."> -->
						<div class="caption">
							<h3><%= product.name %></h3>
							<p class="description"><%= product.description %></p>
							<p><%= link_to 'Comprar' + number_to_currency(product.price, precision: 0) ,purchases_path(product_id: product.id), method: :post, class: 'btn btn-primary' %> <%= %></p>
						</div>
					</div>
				</div>
				<% end %>

			 <% else %>
				<h2 class="text-center">Esta Categoría no tiene productos relacionados</h2>
			 <% end %>
		</div>
	</div>
</div>

app/views/pages/profile.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>Historial de Compras</h1>
			<h2><%= @user.email %></h2>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2>Compras por pagar</h2>
			<table class="table table-hover table-condensed">
				<thead>
					<th>Imagen</th>
					<th>Producto</th>
					<th>Precio</th>
					<th>Fecha</th>
					<th>Estado</th>
					<% if current_user.admin? %>
						<th>Opciones</th>
					<% end %>
				</thead>

				<tbody>
					<% @pending_purchases.each do |purchase| %>
						<tr>
							<td><%= image_tag purchase.product.image.url(:micro_thumb)%></td>
							<td><%= purchase.product.name %></td>
							<td><%= purchase.product.price %></td>
							<td><%= purchase.product.created_at.strftime("Comprado el %d de %B de %Y") %></td>
							<td class="danger"><%= purchase.status.humanize %></td>
							<% if current_user.admin? %>
								<td><%= link_to 'Pagar', purchase_path(id: purchase.id, user_id: purchase.user_id),method: :patch, class: 'btn btn-success' %>-<%= link_to 'Eliminar',purchase_path(id: purchase.id, user_id: purchase.user_id),method: :delete, data: {confirm: "¿Estás seguro de eliminar esta compra?"}, class: 'btn btn-danger' %></td>
							<% end %>
						</tr>
					<% end %>
					<% @paid_purchases.each do |purchase| %>
						<tr>
							<td><%= image_tag purchase.product.image.url(:micro_thumb)%></td>
							<td><%= purchase.product.name %></td>
							<td><%= purchase.product.price %></td>
							<td><%= purchase.product.created_at.strftime("Comprado el %d de %B de %Y") %></td>
							<td class="sucess"><%= purchase.status.humanize %></td>
							<% if current_user.admin? %>
								<td><%= link_to 'Eliminar',purchase_path(id: purchase.id, user_id: purchase.user_id),method: :delete, data: {confirm: "¿Estás seguro de eliminar esta compra?"}, class: 'btn btn-danger'%></td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>