config/routes.rb
Rails.application.routes.draw do
  	
  	root 'pages#home'
  	devise_for :users
	 resources :categories
    resources :products
    resources :purchases
    
    get 'profile' => 'pages#profile'

    get 'dashboard' => 'purchases#dashboard'

   
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


    #get 'welcome' => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<div class="alerts text-center">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice]  %>
        </div>
      <% elsif flash[:alert] %>
         <div class="alert alert-danger">
            <%= flash[:alert]  %>
         </div>
      <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <p class="arnulfo"><%= link_to "Arnulfo's store", root_path %></p>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to 'Productos',products_path %></li>
            <li><%= link_to 'Categorías',categories_path %></li>
            <li><%= link_to 'Dashboard',dashboard_path %></li>
          </ul>
          <% end %>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            
            <li class="<%= balance_status(current_user) %> balance-status"> 
              <%= link_to profile_path(id: current_user.id) do %>
              Saldo: <%= number_to_currency(Purchase.balance(current_user),precision: 0) %>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email.split('@')[0] %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Mi perfil',profile_path(id: current_user.id) %></li>
                <li><%= link_to 'Cerrar Sesión',destroy_user_session_path,method: :delete %></li>
              </ul>
            </li>
            <% else %>
                <li><%= link_to 'Iniciar Sesión',new_user_session_path %></li>
                <li><%= link_to 'Registrarse',new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaTiendaDeMemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

<script>
  $('.alert').fadeIn(500).css("opacity","0.85").delay( 6000 ).slideUp( 1000 );
  $('.alerts').on('click','.alert',function(){ $(this).remove() });
</script>